### ISSUE TITLE
send update notifications on dry run

### ISSUE THREAD

**Issue by eppixx** [pyouroboros/ouroboros#170]
I would like to receive which containers have updates available through notifications using the "--dry-run" flag.
Currently it only sends the time it started looking for updates and when it will start the next time. The updates are only noticable through the logs.

**Comment by DirtyCajunRice** [comment]
Out of curiosity, by what means are you running it with dry run and are not at the console? (since dry run forces run once)

**Comment by eppixx** [comment]
I am interested in the notification feature, which watchtower doesn't have. So I tried it out with dry-run.
Is there a reason why it shouldn't output which updates it would run?

**Comment by DirtyCajunRice** [comment]
Mainly because giving you a notification does not ensure you are going to act on that notification. If you are not acting on the update, you will get an update every interval with the exact same information. If you are dry-running it, the goal of dry-run (as it is in many programs, like letsencrypt for example) is to "test" what would happen. Not to be an automation tool for automating automation.

**Comment by eppixx** [comment]
Shouldn't this what would happen scenario also include what would have been updated.
The dry run already gives out a notification. Why not fill it with something usefull.

**Comment by DirtyCajunRice** [comment]
the startup notification is to test that notifications are working during dry run. And you keep saying it doesnt tell you what is being updated but it does. On the console. Where you should be looking when you dry-run a program

**Comment by eppixx** [comment]
So the notification doesn't include what was updated? Even without using dry-run?

**Comment by DirtyCajunRice** [comment]
There is only a notification after a _successful_ upgrade. Which is about 200 lines of code/logic between where a simple "Can it be upgraded" and "it has been upgraded" sits.

Basically, We completely understand what you are asking for. We understand why YOU want it. We currently have the stance that this is how the functionality should work, and currently do not have plans do change it to notify you redundantly when you already should be at the console to --dry-run ouroboros. If our view changes, we will absolutely open this back up.

Thank you for your suggestion.

**Comment by onedr0p** [comment]
Throwing my hat into the ring. I am interested also in getting notified of image updates when using `--dry-run` but I see where the problem lies with repeated notifications. Perhaps a new flag `--notify-on-dry-run` would suffice and the user can deal with repeated notifications until the images are upgraded.

**Comment by michaelarnauts** [comment]
I'm looking for a way to monitor for outdated containers, so I can update them within an update window (I will probably have to do this manually, without `--dry-run`-ning it). I'm currently monitoring everything through prometheus. This project can almost do what I want, except it should not do the actual update, but set a metric so prometheus can catch when an actual container needs an update.

Is this completely out of scope for this project? Is there a different way to monitor running containers and get notified when I have one that is outdated?
