### ISSUE TITLE
Monitor option default value

### ISSUE THREAD

**Issue by redge76** [pyouroboros/ouroboros#189]
Hi,

I will make the same remark I made on the watchtower repo. (https://github.com/v2tec/watchtower/issues/167)
Don't you think that the default value for the monitor option is "dangerous". It's is too easy to start ouroboros without the monitor option and update a container you don't want to update.
For production environment, this is not good... (exposing docker API + autoupdate is also not a good idea. But I can live with these )

The default behaviour of a software should be to display a log message with the syntax.

**Comment by DirtyCajunRice** [comment]
That is quite subjective. We do have --labels-only which does exactly what you are expecting. If there is no labels applied to your containers it wont continue. We also have --dry-run to allow you to test what _would_ happen. I personally believe its counter intuitive to have a program that, on run, does nothing. To have to "enable" it to do its primary function is quite backwards

**Comment by redge76** [comment]
ouroboros is an update/upgrade system. The most obvious similar software is "apt" or "yum" (I guess you have some linux experience...)
If you start apt without any option, it doesn't do anything.  If you start it with "upgrade" it does let you choose yes or no before applying anything. You have to add the "-y" option to bypass the interactive prompt.
Most programs I can think of that upgrade/shutdown an "unknown" number of programs/services, need some sort of confirmation option to function without any user interaction. (by unknown I mean that you have to use another command to get the list of running container. It's not obvious by just running outoboros)
docker does not pull the latest image by default (except when you start a container for the first time). You have to "force" it by using the "pull" command.

**Comment by DirtyCajunRice** [comment]
every single example you have given are command line utilities that are of a user input, non automated fashion. Ouroboros does not fit into any of those circumstances as it is an automation program. If you wanted to treat ouroboros like apt:
```
apt list —upgradable
==
ouroboros —dry-run
——————————-
apt upgrade -y
==
ouroboros —run-once
——————————-
```
It is not designed to be ran as a cli utility only and is automation oriented. if you only want to do it yourself, the above 2 examples are as close as you are going to get

**Comment by redge76** [comment]
my point is:
ouroboros
==
watch -n 300 apt upgrade -y

no option ---> upgrade everything every 300s

What I think is safe:
ouroboros
==
apt

I can't thing of any other upgrade system that start as a daemon and starts upgrading everything by default. (Maybe microsoft windows update.... but the default  automatic reboot at 3:00AM is a PITA)

**Comment by DirtyCajunRice** [comment]
I understand what you are asking for, but this is not a command line utility. It IS a daemon as you have surmised. You cant think of any others because its not intended to be like your examples. What you want as the default functionality is non-sequitur to the purpose, scope or philosophy of ouroboros. “Safe” is reading the manual, understanding the tool you have chosen to use, and configuring it appropriately.
This is further explained when you dig deeper into the scope of the project. It is a program that is designed to maintain docker containers, and primarily ran as.. a docker container. Docker's philosophy on variables are to put them in the environment and then read from it. If all configuration is in the environment, there are no command line flags. Nor should there be.
As a summation of that scope, command line arguments whatsoever are a user convenience that we have left in from the original design of ouroboros but do not drive the majority of configurations.
We appreciate your feedback and intent to contribute meaningful content to the project, but in this circumstance it is not something we are interesting in changing the entire design of ouroboros around. If this opinion ever changes, we will be sure to re-open this issue.

**Comment by redge76** [comment]
OK then thx for your reply.
I do understand your point.
Also thanks for this great software.
