### ISSUE TITLE
Discord notifications missing "card"

### ISSUE THREAD

**Issue by sjabby** [pyouroboros/ouroboros#244]
Discord notifications used to look like this:
![image](https://user-images.githubusercontent.com/27990031/53442151-e2290800-3a08-11e9-8672-3a00a2eb4c9d.png)

Now looking like this:
![image](https://user-images.githubusercontent.com/27990031/53442162-ed7c3380-3a08-11e9-9c8c-379b22a112ee.png)
![image](https://user-images.githubusercontent.com/27990031/53442183-fc62e600-3a08-11e9-8c7d-0404d36a6e19.png)

**Comment by caronc** [comment]
Try adding **?thumbnail=Yes** to your URL.

**Comment by sjabby** [comment]
Same.

I have this in my compose file:

`- NOTIFIERS="discord://538xxxxxxxxxxxxx/a7Fp-j3Lxxxxxxxxxxxxxxxxxxxplu5LtwOdER?thumbnail=Yes" `

**Comment by caronc** [comment]
hmm...
Could you next try adding **?thumbnail=Yes&format=markdown** to your URL and let me know?

**Comment by DirtyCajunRice** [comment]
hey caronc. i chalked it up to the enhancements you have made and just hadnt had a chance to fix it downstream here.

**Comment by sjabby** [comment]
![image](https://user-images.githubusercontent.com/27990031/53655856-b8165680-3c51-11e9-8673-fbe7c8783fd6.png)
Works!

**Comment by caronc** [comment]
@DirtyCajunRice That's okay :slightly_smiling_face:. You honestly can't be that many commits behind. 

@sjabby Awesome!

FYI: The problem (well... if it is), is actually upstream:
* The thumbnail issue is tied to [this commit](https://github.com/caronc/apprise/commit/237a12284704d07276434b7a2fc1863a92fa8bfc).  The description of the commit was to reflect the documentation (the irony is that now it doesn't). Personally though, i find the images included in every post (to Discord) seemed kind of overkill, big, and really ugly _IMO_.  I'm on the fence on updating the docs to reflect this or rolling back.
* The _markdown_ was removed as the being default because it _really_ breaks the use of Discord from the command line (piping shell commands etc; the hashtag that appears as comments in just about every file looks really busted up when markdown is automatically applied to something that isn't).  A format of _text_ is the new default going forward, but you can optionally set the `?markdown=True` flag in the future to work around this.  Unfortunately I don't really have any good standards in place yet for what certain default settings per notification service should be.

**Comment by DirtyCajunRice** [comment]
Ill close this and reference it if anyone else has this issue. Thanks @caronc
