### ISSUE TITLE
Use publicly accessible build system

### ISSUE THREAD

**Issue by paulfantom** [pyouroboros/ouroboros#308]
This application to work needs access to docker socket which in turn gives root access to host machine. With that in mind it would be nice to expose how ouroboros images are made and NOT use hidden Jenkins host.

This can be easily accomplished by using CI system like travis or circle CI for majority of tests and using advanced automated build system in docker hub (simple one won't fly due to cross-arch images). 
More on using advanced docker automated build system to build cross-arch images can be found in https://github.com/docker/hub-feedback/issues/1261.

**Comment by DirtyCajunRice** [comment]
TravisCI is a corrupt company now after being bought out and does not natively support arm. Jenkins is open to the public and the jenkinsfile is in the repo. there is nothing hidden whatsoever.

In addition, the docker socket can be swapped for the tcp connection, both of which only give access to the docker daemon, not the root machine.

Where are you coming up with this propaganda?

**Comment by angrycuban13** [comment]
tHiS ApPlIcAtIoN To wOrK NeEdS AcCeSs tO DoCkEr sOcKeT WhIcH In tUrN GiVeS RoOt aCcEsS To hOsT MaChInE. wItH ThAt iN MiNd iT WoUlD Be nIcE To eXpOsE HoW OuRoBoRoS ImAgEs aRe mAdE AnD NoT UsE HiDdEn jEnKiNs hOsT.  ThIs cAn bE EaSiLy aCcOmPlIsHeD By uSiNg cI SyStEm lIkE TrAvIs oR CiRcLe cI FoR MaJoRiTy oF TeStS AnD UsInG AdVaNcEd aUtOmAtEd bUiLd sYsTeM In dOcKeR HuB (sImPlE OnE WoN'T FlY DuE To cRoSs-aRcH ImAgEs). mOrE On uSiNg aDvAnCeD DoCkEr aUtOmAtEd bUiLd sYsTeM To bUiLd cRoSs-aRcH ImAgEs cAn bE FoUnD In dOcKeR/HuB-FeEdBaCk#1261.

**Comment by angrycuban13** [comment]
Hmm

**Comment by paulfantom** [comment]
Jenkins might be open, but it is installed somewhere. This place is not publicly accessible, there is no logs, nothing. You are publishing software which needs gets superuser access to any host it is running on and you don't provide any visibility into how it is created.
Travis is one of the options, if you don't like it use circleCI, droneCI, whatever you want. Important factor here is visibility. Minimal case is to use docker automated build system provided by docker hub itself.

> Jenkins is open to the public and the jenkinsfile is in the repo

There are no links to this host in docs and fact of having Jenkinsfile in repo doesn't mean that it is used by Jenkins.

> docker socket can be swapped for the tcp connection, both of which only give access to the docker daemon

Please read official docker documentation on what do you get when you have access to docker daemon https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface

---
As for less technical part:

First of all thank you for presenting your technical knowledge. Up to this point I didn't know if I should use ouroboros or watchtower. Now I know.

> TravisCI is a corrupt company now after being bought out and quietly/without reason firing over 50 percent of the former employees

I am aware of what is happening at TravisCI, their office is quite close from mine and we frequently meet at meetups. No need to present your views.

> Where are you coming up with this propaganda?

Your README.md file states that "All contributions are welcome!" so I wonder where this hostility is coming from.

**Comment by DirtyCajunRice** [comment]
There are logs for literally every single build? If you are uncomfortable with navigating an application you should just ask for help with navigation. [jenkins](https://jenkins.cajun.pro) > Ouroboros > Branch >Build # > Console Output. Here is a link to the latest develop build just to further prove that navigation [here](https://jenkins.cajun.pro/job/Ouroboros/job/develop/10/console) . The pipeline is also visible proving the jenkinsfile is being used [here](https://jenkins.cajun.pro/job/Ouroboros/job/develop/10/flowGraphTable/) just to help any other readers. Since the visibility is identical there is 0 valid reasoning to move when they are functionally the same AND we can build our arm images for our users without bulk. 

Docker security points that you are neglecting:
1. Docker runs via the root user _by default_ and the system administrator has every opportunity to change the user/group that runs the daemon. This is not the responsibility of ouroboros. 
2. Ouroboros code is open source and you have every opportunity to point out any malicious code within it (that does not exist)
3. The images ouroboros updates are created and ran by the user _prior_ to ouroboros. It is only doing what you tell it to. Remember. Computers and code are deterministic. They do exactly what you tell them to do. No more/No less.
---
On the less technical part:
>First of all thank you for presenting your technical knowledge. Up to this point I didn't know if I should use ouroboros or watchtower. Now I know.

If you have made a summation of my technical knowledge off of a disagreement with your statements, I worry you may be too quick to judge on many other things.
>I am aware of what is happening at TravisCI, their office is quite close from mine and we frequently meet at meetups. No need to present your views.

My views dictate my decisions on a project i maintain, and love that I can state them freely!
>Your README.md file states that "All contributions are welcome!" so I wonder where this hostility is coming from.

Im not sure if you are side-stepping your own statements or just blatantly unaware? Contributions are absolutely welcome. Code contributions are welcome and will be assessed. That does not mean they will always be accepted. Positive thought contributions are also welcome. Blatantly incorrect and negatively impacting comments will not and will be addressed as such like:
>This application to work needs access to docker socket which in turn gives root access to host machine.

Since it needs access to EITHER a tcp or docker socket that is not explicitly true and root access is decided by the administrator running the daemon not by ouroboros
>it would be nice to expose how ouroboros images are made and NOT use hidden Jenkins host.

All of that is blatantly wrong and you spent 0 time attempting to validate your own claims.

**Comment by paulfantom** [comment]
From docker docs, section `Post-installation steps for Linux` available at https://docs.docker.com/install/linux/linux-postinstall/. Literally 4th sentence:

> The Docker daemon always runs as the root user.

**Comment by DirtyCajunRice** [comment]
Editing docker.service and making a user with appropriate permissions does allow this to be changed. It does require a deep understanding of permissions throughout your os's installation and is very tedious but can be done nevertheless. I personally think its asinine but you seem very worried about an attack vector on something you are choosing to spin up, whether it be ouroboros or watchtower or any other flavor. 

I have no need of "expertise" from a redhat Quality Engineer. CoreOS has shown the world how that works. Ignoring your statements and taking my response as the first hostile answer is hilariously short-sided.
