### ISSUE TITLE
Slack won't work

### ISSUE THREAD

**Issue by Ylawy** [pyouroboros/ouroboros#313]
Hi,

I'm using ouroboros on a Synology and I'm trying to set up Slack for notifications. This is how I start the docker container
`sudo docker run -d --name ouroboros -v /run/docker.sock:/var/run/docker.sock -e NOTIFIERS=slack://tokenA/tokenB/tokenC -e TZ=Europe/Berlin -e Latest=true -e CLEANUP=true -e INTERVAL=86300 -e LOG_LEVEL=info pyouroboros/ouroboros`

However I always receive the following error message in the docker log section:

> 2019-05-29 16:12:29 : ERROR : Apprise : Could not load URL: ********t195P
2019-05-29 16:12:29 : ERROR : Apprise : Failed to load notification url: ********t195P
2019-05-29 16:12:29 : ERROR : notifiers : Could not add notifier ********t195P

what is the problem here? I tried other webbooks without luck. I already read the apprise wiki but couldn't figure out what I did wrong. Any ideas? Help is much appreciated. Ouroboros is great!

**Comment by caronc** [comment]
This is related to [this (Apprise) PR](https://github.com/caronc/apprise/pull/108).  For now just add **#general** or whatever channel you want to the end of the URL.  This has already been fixed upstream, but i just have not had a time to make an official release out of it yet which is why it's surfacing in Ouroboros.

Hence change your URL (for now) to:
`slack://TokenA/TokenB/TokenC/#general`

**Comment by Ylawy** [comment]
That solved the problem! Thank you.
