### ISSUE TITLE
Logo/Icon not showing up in Slack notifications

### ISSUE THREAD

**Issue by raman325** [pyouroboros/ouroboros#333]
Hi,

I noticed that apprise supports sending a logo/icon for targets that support it, and it looks like you have some code to add the logo in, but when I receive notifications from ouroboros I see my default webhook icon instead of the ouroboros logo. Is this intentional?

**Comment by raman325** [comment]
Actually, nevermind, I see it now at the bottom. Is it possible to also change the icon for the webhook that's posting the message (I have set the default to that info icon)?

![image](https://user-images.githubusercontent.com/7243222/64315689-c5a1f580-cf80-11e9-8267-65bf57fb0471.png)

**Comment by blambert1080** [comment]
Looking more into this, Apprise is functioning as expected. Apprise does not create the WebHook but just uses it as a channel to post relevant information through the WebHook. Therefore there is no way for Apprise to modify the WebHook Icon because this is configured by the Workspace Admin.  

In order to change the large "Icon" you will have to do this manually. Here is a .png you can use for the WebHook: https://github.com/pyouroboros/ouroboros/blob/master/assets/ouroboros_logo_primary.png

**Comment by raman325** [comment]
Thanks for responding. I looked into this and it looks like the issue is that Apprise has no way to change the `icon_url` parameter of the Slack notification payload. I will submit an enhancement request there.
