### ISSUE TITLE
issue with NotifyEmail with ouroboros in container

### ISSUE THREAD

**Issue by nesys** [pyouroboros/ouroboros#367]
Hi folks,

I've installed  ouroboros in a container (version 1.4.3-master)
When I start my container, I see the error "NotifyEmail a connection error occurred sending Email notification to smtp.gmail.com"

my account is name.domain.com, but my domain is managed by Google (G Suite) so the smtp is smtp.gmail.com

here my NOTIFIERS variable: "mailtos://name:app_password@domain.com?smtp=smtp.gmail.com&from=ouroboros@domain.com"

Any suggestion?
Andrea

**Comment by circa10a** [comment]
Ouroboros simply uses [apprise](https://github.com/caronc/apprise) for notifications. please refer their documentation for configuration.

**Comment by caronc** [comment]
@nesys I think you're close.  Here is the [mail](https://github.com/caronc/apprise/wiki/Notify_email) configuration.

You may be doing everything correctly, but just need to set a different secure mode:

For example, if your account is `name.domain.com` like you said but you know you need to access `smtp.gmail.com`, your URL might look like this:

- `mailtos://user:pass@name.domain.com?smtp=name.domain.com`

If you're username is actually a full email address, you could write the URL like this:

- `mailtos://name.domain.com?smtp=name.domain.com&user=myuser@name.domain.com&password=mypass`

By default, `mailtos://` uses `starttls`; if this isn't supported, you could also try using `ssl` instead.  Simply add `&mode=ssl` to your URL. Perhaps now it looks like:

- `mailtos://name.domain.com?smtp=name.domain.com&user=myuser@name.domain.com&password=mypass&mode=ssl`

If this STILL doesn't work, you might need to open your mail settings in the email program you actually use.  Something is amiss.

The Apprise `mailtos://` is actually super powerful and can make your life really easy EXCEPT when using custom SMTP servers (which sounds like your case).  The URL then gets a wee bit hairy; but once you get it right, you'll never have to change it again (so that part is good).

Hopefully this info helps
